//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.23 at 09:43:29 PM ART 
//


package com.example.backend.iso20022.pacs002;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExternalStatusReason1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="ExternalStatusReason1Code"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DS01"/&gt;
 *     &lt;enumeration value="DS02"/&gt;
 *     &lt;enumeration value="DS03"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ExternalStatusReason1Code")
@XmlEnum
public enum ExternalStatusReason1Code {

    @XmlEnumValue("DS01")
    DS_01("DS01"),
    @XmlEnumValue("DS02")
    DS_02("DS02"),
    @XmlEnumValue("DS03")
    DS_03("DS03");
    private final String value;

    ExternalStatusReason1Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExternalStatusReason1Code fromValue(String v) {
        for (ExternalStatusReason1Code c: ExternalStatusReason1Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
