//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.23 at 09:43:29 PM ART 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.12", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.backend.iso20022.pacs002;
